// Extracted from the former 45KB single-file App.tsx.

import { useEffect, useState } from 'react'
import { Artwork } from '../components/common/Artwork'
import { Icon } from '../components/common/Icon'
import { prettyTime } from '../lib/format'

export function MetadataInspector({ track, metadata, onClose, onUndo, onSaved }: { track: LibraryTrack | null; metadata: AudioMetadata | null; onClose: () => void; onUndo: () => void; onSaved: () => void }) { const [draft, setDraft] = useState({ title: '', artist: '', album: '', albumArtist: '', year: '', genre: '', trackNumber: '', discNumber: '' }); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); /* Esc closes, like every other panel. */ useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [onClose]); /* Reset the form only for another song or fresh tags, not whenever the library refreshes behind it (that wiped half-typed edits). */ useEffect(() => { setMessage(''); if (metadata) setDraft({ title: metadata.title || track?.title || '', artist: metadata.artist || '', album: metadata.album || track?.album || '', albumArtist: metadata.albumArtist || '', year: metadata.year ? String(metadata.year) : '', genre: metadata.genre || '', trackNumber: String(metadata.trackNumber || ''), discNumber: String(metadata.discNumber || '') }) }, [metadata, track?.id]); // eslint-disable-line react-hooks/exhaustive-deps
 if (!track) return null; const apply = async () => { setSaving(true); setMessage(''); try { const result = await window.electronAPI.updateTrackMetadata({ audioPath: track.audioPath, metadata: draft, backupOriginal: true }); if (result.updated) onSaved(); else setMessage(result.message || 'The tags could not be written.') } catch (error) { setMessage(error instanceof Error ? error.message : 'The tags could not be written.') } finally { setSaving(false) } }; return <aside className="metadata-inspector"><div className="inspector-header"><div><span className="kicker">METADATA INSPECTOR</span><h3>{track.title}</h3><p>{track.audioPath}</p></div><button onClick={onClose} aria-label="Close inspector"><Icon name="close" size={17} /></button></div><div className="inspector-art"><Artwork track={track} large /><div><strong>{metadata?.codec || track.format}</strong><span>{metadata?.lossless ? 'Lossless' : 'Local audio'} · {prettyTime(metadata?.duration ?? track.duration)}</span><small>{metadata?.bitrate ? `${Math.round(metadata.bitrate / 1000)} kbps` : 'Bitrate unavailable'}{metadata?.sampleRate ? ` · ${Math.round(metadata.sampleRate / 1000)} kHz` : ''}</small></div></div><div className="edit-fields">{(['title', 'artist', 'album', 'albumArtist', 'year', 'genre', 'trackNumber', 'discNumber'] as const).map(field => <label key={field}><span>{field === 'albumArtist' ? 'Album artist' : field.replace(/([A-Z])/g, ' $1')}</span><input value={draft[field]} onChange={event => setDraft(current => ({ ...current, [field]: event.target.value }))} /></label>)}</div><div className="inspector-footer"><button className="ghost-button" onClick={onUndo}><Icon name="undo" size={15} /> Undo last edit</button><button className="accent-button" onClick={() => void apply()} disabled={saving}>{saving ? 'Applying…' : 'Apply metadata'}</button></div>{message && <p className="cookie-status bad" role="alert" style={{ margin: '0 0 8px' }}>{message}</p>}<small className="inspector-warning">MP3 tags are written into the file; other formats keep the edit in a small .lyrigen-metadata.json beside the song, which Lyrigen reads first. A backup is kept either way, so Undo last edit puts it back.</small></aside> }
