// Delete previously built artifacts so `release/` only ever holds the build
// you just made. Version numbers live in the file names, so without this every
// bump leaves the old installer behind and it stops being obvious which one to
// run. Everything here is regenerated by `npm run build`.

import { existsSync, readdirSync, rmSync, statSync } from 'node:fs'
import path from 'node:path'

const dir = path.join(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..', 'release')
if (!existsSync(dir)) {
  console.log('release/ does not exist yet; nothing to clean.')
  process.exit(0)
}

let removed = 0
for (const entry of readdirSync(dir)) {
  const target = path.join(dir, entry)
  // win-unpacked is replaced wholesale by the next build; leave it alone so a
  // failed build does not leave you with nothing runnable at all.
  if (entry === 'win-unpacked') continue
  if (!statSync(target).isFile()) continue
  if (!/\.(exe|blockmap|yml|yaml)$/i.test(entry)) continue
  try { rmSync(target, { force: true }); removed += 1; console.log(`removed ${entry}`) } catch (error) {
    console.warn(`could not remove ${entry} — is the app running? (${error.code ?? error.message})`)
  }
}
console.log(removed ? `cleaned ${removed} old artifact${removed === 1 ? '' : 's'}.` : 'nothing to clean.')
